Repository COALBA-Graduation-Project/COALBA-BE, pull requests merged in 2022-11, with the labels that each got.

#2 feat: 스프링 Security 기반 로그인 및 인증 기능
  build.gradle
  src/main/java/com/project/coalba/domain/auth/config/SecurityConfig.java
  src/main/java/com/project/coalba/domain/auth/controller/AuthController.java
  src/main/java/com/project/coalba/domain/auth/dto/GoogleUserInfoDto.java
  src/main/java/com/project/coalba/domain/auth/dto/NaverUserInfoDto.java
  src/main/java/com/project/coalba/domain/auth/dto/request/TokenRequest.java
  src/main/java/com/project/coalba/domain/auth/dto/response/AuthResponse.java
  src/main/java/com/project/coalba/domain/auth/dto/response/TokenResponse.java
  src/main/java/com/project/coalba/domain/auth/entity/User.java
  src/main/java/com/project/coalba/domain/auth/entity/UserPrincipal.java
  src/main/java/com/project/coalba/domain/auth/entity/UserRefreshToken.java
  src/main/java/com/project/coalba/domain/auth/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/project/coalba/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/project/coalba/domain/auth/info/UserInfo.java
  src/main/java/com/project/coalba/domain/auth/info/UserInfoFactory.java
  src/main/java/com/project/coalba/domain/auth/info/impl/GoogleUserInfo.java
  src/main/java/com/project/coalba/domain/auth/info/impl/NaverUserInfo.java
  src/main/java/com/project/coalba/domain/auth/repository/UserRefreshTokenRepository.java
  src/main/java/com/project/coalba/domain/auth/repository/UserRepository.java
  src/main/java/com/project/coalba/domain/auth/service/AuthService.java
  src/main/java/com/project/coalba/domain/auth/token/AuthTokenManager.java
  src/main/java/com/project/coalba/domain/auth/utils/HeaderUtil.java
Labels: ⚙️ Setting, ✨ Feature, 📫 API

#4 feat: 로그인 및 인증 구현사항 수정
  src/main/java/com/project/coalba/domain/auth/controller/UserController.java
  src/main/java/com/project/coalba/domain/auth/dto/GoogleUserInfoDto.java
  src/main/java/com/project/coalba/domain/auth/info/impl/GoogleUserInfo.java
  src/main/java/com/project/coalba/domain/auth/info/impl/NaverUserInfo.java
  src/main/java/com/project/coalba/global/utils/SecurityUtil.java
  src/main/java/com/project/coalba/global/utils/UserUtil.java
Labels: 🐞 BugFix, ✨ Feature, 📫 API

#6 profile 도메인 API 개발
  src/main/java/com/project/coalba/domain/profile/controller/BossProfileController.java
  src/main/java/com/project/coalba/domain/profile/controller/StaffProfileController.java
  src/main/java/com/project/coalba/domain/profile/dto/request/ProfileRequest.java
  src/main/java/com/project/coalba/domain/profile/dto/response/ProfileResponse.java
  src/main/java/com/project/coalba/domain/profile/entity/Boss.java
  src/main/java/com/project/coalba/domain/profile/entity/Staff.java
  src/main/java/com/project/coalba/domain/profile/repository/BossProfileRepository.java
  src/main/java/com/project/coalba/domain/profile/repository/StaffProfileRepository.java
  src/main/java/com/project/coalba/domain/profile/service/BossProfileService.java
  src/main/java/com/project/coalba/domain/profile/service/StaffProfileService.java
Labels: ✨ Feature, 📫 API

#14 workspace, workspaceMember 도메인 API 개발
  build.gradle
  src/main/java/com/project/coalba/domain/profile/entity/Boss.java
  src/main/java/com/project/coalba/domain/profile/entity/Staff.java
  src/main/java/com/project/coalba/domain/profile/repository/BossProfileRepository.java
  src/main/java/com/project/coalba/domain/profile/repository/StaffProfileRepository.java
  src/main/java/com/project/coalba/domain/profile/repository/custom/StaffProfileRepositoryCustom.java
  src/main/java/com/project/coalba/domain/profile/repository/custom/StaffProfileRepositoryImpl.java
  src/main/java/com/project/coalba/domain/profile/service/BossProfileService.java
  src/main/java/com/project/coalba/domain/profile/service/StaffProfileService.java
  src/main/java/com/project/coalba/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/project/coalba/domain/schedule/service/ScheduleService.java
  src/main/java/com/project/coalba/domain/workspace/controller/BossWorkspaceController.java
  src/main/java/com/project/coalba/domain/workspace/controller/StaffWorkspaceController.java
  src/main/java/com/project/coalba/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/project/coalba/domain/workspace/dto/request/SearchDateTime.java
  src/main/java/com/project/coalba/domain/workspace/dto/request/WorkspaceRequest.java
  src/main/java/com/project/coalba/domain/workspace/dto/request/WorkspaceUpdateRequest.java
  src/main/java/com/project/coalba/domain/workspace/dto/response/WorkspaceListResponse.java
  src/main/java/com/project/coalba/domain/workspace/dto/response/WorkspaceMemberInfoListResponse.java
  src/main/java/com/project/coalba/domain/workspace/dto/response/WorkspaceMemberInfoResponse.java
  src/main/java/com/project/coalba/domain/workspace/dto/response/WorkspaceOneResponse.java
  src/main/java/com/project/coalba/domain/workspace/dto/response/WorkspaceResponse.java
  src/main/java/com/project/coalba/domain/workspace/dto/response/WorkspaceStaffListResponse.java
  src/main/java/com/project/coalba/domain/workspace/dto/response/WorkspaceStaffResponse.java
  src/main/java/com/project/coalba/domain/workspace/entity/Workspace.java
  src/main/java/com/project/coalba/domain/workspace/entity/WorkspaceMember.java
  src/main/java/com/project/coalba/domain/workspace/entity/WorkspaceMemberInfo.java
  src/main/java/com/project/coalba/domain/workspace/entity/enums/Position.java
  src/main/java/com/project/coalba/domain/workspace/mapper/WorkspaceMapper.java
  src/main/java/com/project/coalba/domain/workspace/repository/WorkspaceMemberRepository.java
  src/main/java/com/project/coalba/domain/workspace/repository/WorkspaceRepository.java
  src/main/java/com/project/coalba/domain/workspace/repository/custom/WorkspaceRepositoryCustom.java
  src/main/java/com/project/coalba/domain/workspace/repository/custom/WorkspaceRepositoryImpl.java
  src/main/java/com/project/coalba/domain/workspace/service/BossWorkspaceService.java
  src/main/java/com/project/coalba/domain/workspace/service/StaffWorkspaceService.java
  src/main/java/com/project/coalba/domain/workspace/service/WorkspaceService.java
  src/main/java/com/project/coalba/global/config/WebMvcConfig.java
  src/main/java/com/project/coalba/global/utils/ProfileUtil.java
Labels: ⚙️ Setting, ✨ Feature, 📫 API, 🔨 Refactor

#15 쪽지 API 개발
  src/main/java/com/project/coalba/domain/message/controller/BossMessageController.java
  src/main/java/com/project/coalba/domain/message/controller/StaffMessageController.java
  src/main/java/com/project/coalba/domain/message/dto/request/MessageRequest.java
  src/main/java/com/project/coalba/domain/message/dto/response/MessageResponse.java
  src/main/java/com/project/coalba/domain/message/repository/MessageRepository.java
  src/main/java/com/project/coalba/domain/message/repository/MessageRepositoryCustom.java
  src/main/java/com/project/coalba/domain/message/repository/MessageRepositoryImpl.java
  src/main/java/com/project/coalba/domain/message/service/BossMessageService.java
  src/main/java/com/project/coalba/domain/message/service/StaffMessageService.java
  src/main/java/com/project/coalba/global/utils/ProfileUtil.java
Labels: ✨ Feature, 📫 API
