Repository COALBA-Graduation-Project/COALBA-BE, pull requests merged in 2023-01, with the labels that each got.

#20 대타근무 요청 API 구현
  src/main/java/com/project/coalba/domain/profile/repository/BossProfileRepository.java
  src/main/java/com/project/coalba/domain/profile/repository/custom/BossProfileRepositoryCustom.java
  src/main/java/com/project/coalba/domain/profile/repository/custom/BossProfileRepositoryImpl.java
  src/main/java/com/project/coalba/domain/profile/service/BossProfileService.java
  src/main/java/com/project/coalba/domain/schedule/entity/Schedule.java
  src/main/java/com/project/coalba/domain/substituteReq/controller/BossSubstituteReqController.java
  src/main/java/com/project/coalba/domain/substituteReq/controller/StaffSubstituteReqController.java
  src/main/java/com/project/coalba/domain/substituteReq/dto/request/CreateSubstituteReqRequest.java
  src/main/java/com/project/coalba/domain/substituteReq/dto/response/BothDetailSubstituteReqResponse.java
  src/main/java/com/project/coalba/domain/substituteReq/dto/response/BothSubstituteReqResponse.java
  src/main/java/com/project/coalba/domain/substituteReq/dto/response/ReceivedDetailSubstituteReqResponse.java
  src/main/java/com/project/coalba/domain/substituteReq/dto/response/ReceivedSubstituteReqResponse.java
  src/main/java/com/project/coalba/domain/substituteReq/dto/response/SentDetailSubstituteReqResponse.java
  src/main/java/com/project/coalba/domain/substituteReq/dto/response/SentSubstituteReqResponse.java
  src/main/java/com/project/coalba/domain/substituteReq/dto/response/SubstituteReqsResponse.java
  src/main/java/com/project/coalba/domain/substituteReq/dto/response/YearMonth.java
  src/main/java/com/project/coalba/domain/substituteReq/entity/SubstituteReq.java
  src/main/java/com/project/coalba/domain/substituteReq/entity/enums/SubstituteReqStatus.java
  src/main/java/com/project/coalba/domain/substituteReq/repository/SubstituteRepository.java
  src/main/java/com/project/coalba/domain/substituteReq/repository/SubstituteRepositoryImpl.java
  src/main/java/com/project/coalba/domain/substituteReq/repository/SubstituteReqRepositoryCustom.java
  src/main/java/com/project/coalba/domain/substituteReq/repository/dto/BothSubstituteReqDto.java
  src/main/java/com/project/coalba/domain/substituteReq/repository/dto/SubstituteReqDto.java
  src/main/java/com/project/coalba/domain/substituteReq/service/BossSubstituteReqService.java
  src/main/java/com/project/coalba/domain/substituteReq/service/StaffSubstituteReqService.java
  src/main/java/com/project/coalba/global/exception/BusinessException.java
  src/main/java/com/project/coalba/global/exception/ErrorCode.java
  src/main/java/com/project/coalba/global/exception/ErrorResponse.java
  src/main/java/com/project/coalba/global/exception/GlobalExceptionHandler.java
  src/main/java/com/project/coalba/global/utils/ProfileUtil.java
Labels: ✨ Feature, 📫 API, 🔨 Refactor

#28 auth, profile, workspace, schedule 도메인 마무리
  src/main/java/com/project/coalba/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/project/coalba/domain/auth/info/impl/GoogleUserInfo.java
  src/main/java/com/project/coalba/domain/auth/info/impl/NaverUserInfo.java
  src/main/java/com/project/coalba/domain/auth/service/AuthService.java
  src/main/java/com/project/coalba/domain/auth/token/AuthTokenManager.java
  src/main/java/com/project/coalba/domain/profile/repository/StaffProfileRepositoryImpl.java
  src/main/java/com/project/coalba/domain/profile/service/BossProfileService.java
  src/main/java/com/project/coalba/domain/profile/service/StaffProfileService.java
  src/main/java/com/project/coalba/domain/schedule/controller/BossScheduleReportController.java
  src/main/java/com/project/coalba/domain/schedule/controller/StaffScheduleReportController.java
  src/main/java/com/project/coalba/domain/schedule/dto/response/BossWorkReportDateListResponse.java
  src/main/java/com/project/coalba/domain/schedule/dto/response/StaffWorkReportDateListResponse.java
  src/main/java/com/project/coalba/domain/schedule/entity/Schedule.java
  src/main/java/com/project/coalba/domain/schedule/repository/ScheduleRepositoryCustom.java
  src/main/java/com/project/coalba/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/project/coalba/domain/schedule/service/BossScheduleService.java
  src/main/java/com/project/coalba/domain/schedule/service/ScheduleService.java
  src/main/java/com/project/coalba/domain/schedule/service/ScheduleValidator.java
  src/main/java/com/project/coalba/domain/schedule/service/StaffScheduleService.java
  src/main/java/com/project/coalba/domain/schedule/service/WorkReportService.java
  src/main/java/com/project/coalba/domain/workspace/controller/BossWorkspaceController.java
  src/main/java/com/project/coalba/domain/workspace/dto/response/WorkspaceBriefListResponse.java
  src/main/java/com/project/coalba/domain/workspace/mapper/WorkspaceMapper.java
  src/main/java/com/project/coalba/domain/workspace/repository/WorkspaceMemberRepository.java
  src/main/java/com/project/coalba/domain/workspace/repository/WorkspaceRepository.java
  src/main/java/com/project/coalba/domain/workspace/repository/WorkspaceRepositoryImpl.java
  src/main/java/com/project/coalba/domain/workspace/service/BossWorkspaceService.java
  src/main/java/com/project/coalba/global/exception/ErrorCode.java
  src/main/java/com/project/coalba/global/exception/ErrorResponse.java
  src/main/java/com/project/coalba/global/exception/FieldErrorResponse.java
  src/main/java/com/project/coalba/global/exception/GlobalExceptionHandler.java
  src/main/java/com/project/coalba/global/utils/ProfileUtil.java
Labels: 🐞 BugFix, ✨ Feature, 📫 API, 🔨 Refactor

#30 인증(로그인) api 변경사항 구현
  src/main/java/com/project/coalba/domain/auth/controller/AuthController.java
  src/main/java/com/project/coalba/domain/auth/controller/UserController.java
  src/main/java/com/project/coalba/domain/auth/dto/request/AuthRequest.java
  src/main/java/com/project/coalba/domain/auth/entity/User.java
  src/main/java/com/project/coalba/domain/auth/entity/UserRefreshToken.java
  src/main/java/com/project/coalba/domain/auth/info/impl/GoogleUserInfo.java
  src/main/java/com/project/coalba/domain/auth/info/impl/NaverUserInfo.java
  src/main/java/com/project/coalba/domain/auth/info/impl/dto/GoogleUserInfoDto.java
  src/main/java/com/project/coalba/domain/auth/info/impl/dto/NaverUserInfoDto.java
  src/main/java/com/project/coalba/domain/auth/service/AuthService.java
  src/main/java/com/project/coalba/domain/auth/token/AuthTokenManager.java
  src/main/java/com/project/coalba/domain/auth/token/UserPrincipal.java
  src/main/java/com/project/coalba/global/utils/EncryptionUtil.java
  src/main/java/com/project/coalba/global/utils/SecurityUtil.java
Labels: ✨ Feature
